version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: public
      POSTGRES_DB: farm_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
